<template>
<div>
<div id=status>
            <div id="time"></div>
</div>

<div id=category>
<div class=category-container>
                    <div class=cg-name>
                        <span>Animal</span>
                    </div>
                    <div class= cg-img>
                        <img src="../assets/category/cat.png">
                    </div>
        </div>
        <div class=category-container>
                    <div class=cg-name>
                        <span>Country</span>
                    </div>
                    <div class= cg-img>
                            <img src="../assets/category/south-korea.png">
                    </div>
        </div>
        <div class=category-container>
                    <div class=cg-name>
                        <span>Food</span>
                    </div>
                    <div class= cg-img>
                            <img src="../assets/category/apple.png">
                    </div>
        </div>
        <div class=category-container>
                    <div class=cg-name>
                        <span>Job</span>
                    </div>
                    <div class= cg-img>
                            <img src="../assets/category/firefighter.png">
                    </div>
        </div>
        <div class=logo>
            <div class=icon>
                <img src="../assets/category/avocado.png" height="100%" width="100%">
            </div>
        </div>
        <div class=category-container>
                    <div class=cg-name>
                        <span>Nature</span>
                    </div>
                    <div class= cg-img>
                            <img src="../assets/category/sprout.png">
                    </div>
        </div>
        <div class=category-container>
                    <div class=cg-name>
                        <span>School</span>
                    </div>
                    <div class= cg-img>
                            <img src="../assets/category/blackboard.png">
                    </div>
        </div>
        <div class=category-container>
            
                    <div class=cg-name>
                        <span>Sports</span>
                    </div>
                    <div class= cg-img>
                            <img src="../assets/category/football.png">
                    </div>
        </div>
        <div class=category-container>
                    <div class=cg-name>
                        Vehicle
                    </div>
                            <img class= "cg-img" src="../assets/category/car.png">
        </div>
    </div>
    <div id = footer> </div>

</div>
</template>

<style>
        /* ----------------------------------------------
             * Generated by Animista on 2019-7-7 15:35:28
             * w: http://animista.net, t: @cssanimista
             * ---------------------------------------------- */

        @-webkit-keyframes heartbeat {
            from {
                -webkit-transform: scale(1);
                transform: scale(1);
                -webkit-transform-origin: center center;
                transform-origin: center center;
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out
            }

            10% {
                -webkit-transform: scale(.91);
                transform: scale(.91);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            17% {
                -webkit-transform: scale(.98);
                transform: scale(.98);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out
            }

            33% {
                -webkit-transform: scale(.87);
                transform: scale(.87);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            45% {
                -webkit-transform: scale(1);
                transform: scale(1);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out
            }
        }

        @keyframes heartbeat {
            from {
                -webkit-transform: scale(1);
                transform: scale(1);
                -webkit-transform-origin: center center;
                transform-origin: center center;
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out
            }

            10% {
                -webkit-transform: scale(.91);
                transform: scale(.91);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            17% {
                -webkit-transform: scale(.98);
                transform: scale(.98);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out
            }

            33% {
                -webkit-transform: scale(.87);
                transform: scale(.87);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            45% {
                -webkit-transform: scale(1);
                transform: scale(1);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out
            }
        }

        /* ----------------------------------------------
 * Generated by Animista on 2019-7-7 17:10:30
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

        @-webkit-keyframes rotate-in-ver {
            0% {
                -webkit-transform: rotateY(-360deg);
                transform: rotateY(-360deg);
                opacity: 0
            }

            100% {
                -webkit-transform: rotateY(0deg);
                transform: rotateY(0deg);
                opacity: 1
            }
        }

        @keyframes rotate-in-ver {
            0% {
                -webkit-transform: rotateY(-360deg);
                transform: rotateY(-360deg);
                opacity: 0
            }

            100% {
                -webkit-transform: rotateY(0deg);
                transform: rotateY(0deg);
                opacity: 1
            }
        }
        
        body{
            background-image: url('../assets/background/background_2.jpeg');
            background-repeat:no-repeat;
            background-size: cover;
        }

        #status {
            height: 25%
        }

        #category {
            position: absolute;
            left: 50%;
            transform: translateX(-50%);
            height: 50%;
            padding: 30px;
            margin-top: 40px;
            margin-bottom: 40px;
        }

        .category-container {
            float: left;
            padding-left: 7px;
            padding-right: 7px;
            padding-top: 7px;
            padding-bottom: 7px;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 10px;
            text-decoration: none;
            width: 25%;
            height: 40%;
            border-radius: 90px;
            background-color: #FFF69E;
            box-shadow: 3px 3px 3px 3px #DCE775;
        }

        #footer{
            height: 25%;
        }

        .logo {
            float: left;
            padding-left: 7px;
            padding-right: 7px;
            padding-top: 7px;
            padding-bottom: 7px;
            margin-top: 0px;
            margin-left: 10px;
            margin-right: 10px;
            width: 25%;
            height: 40%;
            border-radius: 100px;
            -webkit-animation: heartbeat 1.5s ease-in-out infinite both;
            animation: heartbeat 1.5s ease-in-out infinite both
        }

        .cg-name {
            text-align: center;
            margin-top: 5px;    
            font-size: 25px;
            font-family: "Helvetica", "나눔 고딕", serif;
            font-weight: bold;
        }

        #time {
            border:1px solid #558B2F; 
            background-color: #558B2F;
            width:15%; 
            height:100%; 
            line-height:100%; 
            color:#dedede;
            padding-bottom: 5px;
            padding-top: 5px;
            font-size:40px; 
            text-align:center;
        }

        .cg-img{
            margin:auto;
            text-align: center;
        }

    </style>

<script>
   $(document).ready(function(){
            $('.category-container').mouseenter(function () {
                $(this).css('-webkit-animation', 'rotate-in-ver .5s cubic-bezier(.25,.46,.45,.94) both')
                $(this).css('animation', 'rotate-in-ver .5s cubic-bezier(.25,.46,.45,.94) both')
            });
            $('.category-container').click(function () {

            });
        });
export default {
  data() {
    return {
      user: {}
    }
  },
  created: async function () {
    const userId = 'lmj'
    const result = await this.$http.get(`/api/users/${userId}`)
    this.user = result.data;
    console.log(this.user);
    this.printClock();
  },
  methods: {
            printClock() {

            var clock = document.getElementById("time");// 출력할 장소 선택
            var currentDate = new Date();// 현재시간
            var calendar = currentDate.getFullYear() + "-" + (currentDate.getMonth() + 1) + "-" + currentDate.getDate() // 현재 날짜
            var amPm = 'AM'; // 초기값 AM
            var currentHours = addZeros(currentDate.getHours(), 2);
            var currentMinute = addZeros(currentDate.getMinutes(), 2);
            //var currentSeconds = addZeros(currentDate.getSeconds(), 2);

            if (currentHours >= 12) { // 시간이 12보다 클 때 PM으로 세팅, 12를 빼줌
                amPm = 'PM';
                currentHours = addZeros(currentHours - 12, 2);
            }

            clock.innerHTML = currentHours + ":" + currentMinute  + " <span style='font-size:30px;'>" + amPm + "</span>"; //날짜를 출력해 줌

            setTimeout("printClock()", 1000);  // 1초마다 printClock() 함수 호출
        },

        addZeros(num, digit) { // 자릿수 맞춰주기
            var zero = '';
            num = num.toString();
            if (num.length < digit) {
                for (i = 0; i < digit - num.length; i++) {
                    zero += '0';
                }
            }
            return zero + num;
        }
  
}
}
</script>
    